### ISSUE TITLE
футер

### ISSUE THREAD

**Issue by tonyzaa** [xazy06/askeducation#18]
1. убрать забор
2. лого сделать чуть меньше

**Comment by xazy06** [comment]
готово, ждет заливки

**Comment by tonyzaa** [comment]
Скажи, футер будет доступен к редактированию?
Если нет нужно исправить текст:
Консультации проводятся в нашем офисе,
а также по телефону или по Skype:
+7 (499) 322-23-16
Мы работаем с понедельника по пятницу
с 10:00 до 18:00
 Москва, Варшавское шоссе, д.5, офис 30 (2 этаж).

**Comment by xazy06** [comment]
возможно будет текст поправил
