### ISSUE TITLE
города и страны

### ISSUE THREAD

**Issue by tonyzaa** [xazy06/askeducation#19]
Города и страны в админке можно только добавлять и удалять, а переименовать нельзя. Можно ли добавить функцию «переименовать»?

**Comment by xazy06** [comment]
тыкаешь в название и справа будет редактирование

**Comment by xazy06** [comment]
![screencapture-localhost-8080-admin-cities-2020-03-13-03_46_37](https://user-images.githubusercontent.com/7621571/76579461-597aee00-64dd-11ea-8253-ee754778b8b1.png)
